# -*- coding: utf-8 -*-
"""04_nip_asn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aoHFQmgg5RLW0DUcoSsASVVsmrCiv4Lm
"""

#PROGRAM 4
#SKENARIO RELEVAN & TIDAK RELEVAN
nip = input("Masukkan NIP ASN (minimal 8 digit): ")

tahun = int(nip[0:4])
bulan_angka = int(nip[4:6])
tanggal = int(nip[6:8])

if bulan_angka == 1:
    bulan = "Januari"
elif bulan_angka == 2:
    bulan = "Februari"
elif bulan_angka == 3:
    bulan = "Maret"
elif bulan_angka == 4:
    bulan = "April"
elif bulan_angka == 5:
    bulan = "Mei"
elif bulan_angka == 6:
    bulan = "Juni"
elif bulan_angka == 7:
    bulan = "Juli"
elif bulan_angka == 8:
    bulan = "Agustus"
elif bulan_angka == 9:
    bulan = "September"
elif bulan_angka == 10:
    bulan = "Oktober"
elif bulan_angka == 11:
    bulan = "November"
elif bulan_angka == 12:
    bulan = "Desember"
else:
    bulan = "Tidak valid"

# Validasi
if len(nip) < 8:
    print("NIP tidak valid (kurang dari 8 digit).")
elif bulan_angka < 1 or bulan_angka > 12:
    print("Bulan lahir tidak valid (harus antara 01-12. cek digit ke 5 & 6).")
elif tanggal < 1 or tanggal > 31:
    print("Tanggal lahir tidak valid (harus antara 01–31. cek digit ke 7 & 8).")
else:
    print(f"Tanggal Lahir ASN: {tanggal} {bulan} {tahun}")


#NIP 1: 199004182014021802
#NIP 2: 199702232015031903
#NIP 3: 200106312022204235
#INPUT TDK RELEVAN 1: 1990041
#INPUT TDK RELEVAN 2: 199004322014021802
#INPUT TDK RELEVAN 3: 199040232014021802

