# -*- coding: utf-8 -*-
"""03_akar_kuadrat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zvmc1TzoEKmtBADu3ZqqurWWfCHudrVx
"""

#PROGRAM 3
#skenario 1
import math
a = float(input("Masukkan nilai a: "))
b = float(input("Masukkan nilai b: "))
c = float(input("Masukkan nilai c: "))
diskriminan = b**2 - 4*a*c
if diskriminan > 0:
    x1 = (-b + math.sqrt(diskriminan)) / (2*a)
    x2 = (-b - math.sqrt(diskriminan)) / (2*a)
    print(f"Akar real: x1 = {x1:.3f}, x2 = {x2:.3f}")
elif diskriminan == 0:
    x = -b / (2*a)
    print(f"Akar kembar: x = {x:.3f}")
else:
    print("Persamaan hanya memiliki akar-akar imajiner.")

#skenario 2
import math
a = float(input("Masukkan nilai a: "))
b = float(input("Masukkan nilai b: "))
c = float(input("Masukkan nilai c: "))
diskriminan = b**2 - 4*a*c
if diskriminan > 0:
    x1 = (-b + math.sqrt(diskriminan)) / (2*a)
    x2 = (-b - math.sqrt(diskriminan)) / (2*a)
    print(f"Akar real: x1 = {x1:.3f}, x2 = {x2:.3f}")
elif diskriminan == 0:
    x = -b / (2*a)
    print(f"Akar kembar: x = {x:.3f}")
else:
    print("Persamaan hanya memiliki akar-akar imajiner.")

#skenario 3
import math
a = float(input("Masukkan nilai a: "))
b = float(input("Masukkan nilai b: "))
c = float(input("Masukkan nilai c: "))
diskriminan = b**2 - 4*a*c
if diskriminan > 0:
    x1 = (-b + math.sqrt(diskriminan)) / (2*a)
    x2 = (-b - math.sqrt(diskriminan)) / (2*a)
    print(f"Akar real: x1 = {x1:.3f}, x2 = {x2:.3f}")
elif diskriminan == 0:
    x = -b / (2*a)
    print(f"Akar kembar: x = {x:.3f}")
else:
    print("Persamaan hanya memiliki akar-akar imajiner.")